// Copies contract ABIs from Hardhat artifacts into the client as typed consts.
//   pnpm --filter @ossuary/contracts export-abi
import { readFileSync, writeFileSync } from 'node:fs';

const names = ['OssuaryGame', 'Relics'];
let out = '// Generated by packages/contracts/scripts/export-abi.ts. Do not edit.\n\n';
for (const n of names) {
  const art = JSON.parse(readFileSync(`artifacts/contracts/${n}.sol/${n}.json`, 'utf8'));
  out += `export const ${n[0].toLowerCase() + n.slice(1)}Abi = ${JSON.stringify(art.abi, null, 2)} as const;\n\n`;
}
writeFileSync('../../apps/client/chain/abi.ts', out);
console.log('wrote apps/client/chain/abi.ts');
