"""Generates src/levels/charnel.ts from room rectangles.

Editing the level means editing this file and re-running it:
    python tools/gen_charnel.py
"""
import os

W, H = 48, 40
grid = [['#'] * W for _ in range(H)]


def fill(ch, x0, y0, x1, y1):
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            grid[y][x] = ch


# Rooms, in play order. Sector chars are lower case, doors upper case.
fill('a', 2, 2, 9, 8)          # entry crypt
fill('D', 10, 4, 10, 5)        # crypt door
fill('b', 11, 4, 14, 5)        # corridor
fill('h', 15, 2, 30, 10)       # bone hall
for x, y in [(18, 4), (18, 8), (22, 4), (22, 8), (26, 4), (26, 8)]:
    grid[y][x] = 'X'           # pillars
fill('o', 27, 5, 29, 7)        # altar
fill('b', 22, 11, 23, 14)      # hall -> cistern
fill('D', 22, 12, 23, 12)
fill('s', 14, 15, 33, 24)      # slime cistern
fill('w', 14, 19, 33, 20)      # walkway east-west
fill('w', 22, 15, 23, 24)      # walkway north-south
for x0, y0 in [(14, 15), (31, 15), (14, 23), (31, 23)]:
    fill('l', x0, y0, x0 + 2, y0 + 1)   # caster ledges
fill('b', 9, 19, 13, 20)       # cistern -> vault
fill('v', 2, 15, 8, 22)        # red key vault
fill('R', 34, 19, 34, 20)      # red door
fill('b', 35, 19, 37, 20)
fill('f', 38, 12, 46, 27)      # furnace
fill('k', 43, 20, 43, 22)      # stair
fill('K', 44, 20, 46, 22)      # platform with the blue key
fill('B', 40, 28, 41, 28)      # blue door
fill('b', 40, 29, 41, 29)
fill('c', 24, 30, 41, 37)      # chapel
for x, y in [(29, 33), (29, 34), (36, 33), (36, 34)]:
    grid[y][x] = 'X'
fill('D', 23, 33, 23, 34)      # chapel -> exit
fill('e', 18, 32, 22, 35)      # exit antechamber
fill('x', 19, 33, 21, 34)      # sigil

# Wall textures follow the room they face.
wall_for = {'a': '#', 'b': 'M', 'h': '#', 'o': '#', 's': 'M', 'w': 'M', 'l': 'M', 'v': '#',
            'f': 'T', 'k': 'T', 'K': 'T', 'c': '#', 'e': '#', 'x': '#', 'D': 'M', 'R': 'M', 'B': 'M'}
out = [row[:] for row in grid]
for y in range(H):
    for x in range(W):
        if grid[y][x] != '#':
            continue
        for dx, dy in [(1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (-1, -1), (1, -1), (-1, 1)]:
            nx, ny = x + dx, y + dy
            if 0 <= nx < W and 0 <= ny < H and grid[ny][nx] in wall_for:
                out[y][x] = wall_for[grid[ny][nx]]
                break

things = [
    # crypt
    ('ammo', 7, 3), ('opt_item', 3, 7),
    # bone hall
    ('rusher', 20, 6), ('rusher', 24, 3), ('rusher', 25, 9), ('opt_mob', 29, 3), ('opt_mob', 16, 9),
    ('shotgun', 28, 6), ('health', 16, 3), ('shells', 29, 9),
    # cistern
    ('caster', 15, 15), ('caster', 32, 24), ('opt_mob', 32, 15), ('opt_mob', 15, 24), ('rusher', 28, 19),
    ('shells', 22, 24), ('opt_item', 26, 20), ('health', 18, 20),
    # vault
    ('key_red', 4, 18), ('rusher', 6, 16), ('rusher', 6, 21), ('ammo', 3, 21), ('opt_mob', 7, 15), ('armor', 2, 15),
    # furnace
    ('lance', 44, 14), ('heavy', 41, 24), ('caster', 39, 13), ('rusher', 45, 26), ('key_blue', 45, 21),
    ('cells', 39, 26), ('health', 46, 13), ('opt_mob', 42, 18), ('opt_item', 39, 20),
    # chapel
    ('heavy', 34, 34), ('caster', 27, 31), ('caster', 39, 36), ('rusher', 30, 36), ('rusher', 36, 31),
    ('opt_mob', 32, 33), ('opt_mob', 26, 36), ('health', 40, 31), ('shells', 25, 31), ('cells', 41, 37),
    ('armor', 33, 37), ('opt_item', 38, 33),
]
for k, x, y in things:
    assert out[y][x] not in '#MTX', (k, x, y, out[y][x])

rows = ',\n'.join("    '" + ''.join(r) + "'" for r in out)
things_ts = ',\n'.join("    ['%s', %d, %d]" % t for t in things)

HEADER = """import type { LevelDef } from '../level';

// The Charnel Descent. Generated by tools/gen_charnel.py; edit that, not this.
// Crypt -> bone hall (shotgun) -> slime cistern (casters on ledges) -> vault
// (red key) -> red door -> furnace (lance, blue key on the platform) -> blue
// door -> chapel -> exit sigil. Slots marked opt_* change with the day.

export const charnelDescent: LevelDef = {
  name: 'The Charnel Descent',
  sectors: {
    crypt: { floor: 0, ceil: 128, light: '#4a3c6a', lightTop: '#9a6a48', floorTex: 'flagstone', ceilTex: 'plates' },
    duct: { floor: 0, ceil: 96, light: '#303e58', lightTop: '#20283a', floorTex: 'grate', ceilTex: 'plates' },
    doorway: { floor: 0, ceil: 96, light: '#405070', lightTop: '#283450', floorTex: 'grate', ceilTex: 'plates', wallTex: 'metal' },
    hall: { floor: 0, ceil: 192, light: '#8a6438', lightTop: '#2a1c3a', floorTex: 'flagstone', ceilTex: 'plates' },
    altar: { floor: 16, ceil: 192, light: '#b08848', lightTop: '#3a2a40', floorTex: 'grate', ceilTex: 'plates', wallTex: 'brick' },
    slime: { floor: -24, ceil: 160, light: '#3c9a3c', lightTop: '#183018', floorTex: 'slime', ceilTex: 'plates', wallTex: 'metal', damage: 4 },
    walkway: { floor: 0, ceil: 160, light: '#5a7a4a', lightTop: '#1c2c1c', floorTex: 'grate', ceilTex: 'plates', wallTex: 'metal' },
    ledge: { floor: 48, ceil: 160, light: '#6a8a5a', lightTop: '#203020', floorTex: 'plates', ceilTex: 'plates', wallTex: 'metal' },
    vault: { floor: 0, ceil: 128, light: '#a83020', lightTop: '#300810', floorTex: 'flagstone', ceilTex: 'plates' },
    furnace: { floor: 0, ceil: 224, light: '#c06a28', lightTop: '#401808', floorTex: 'grate', ceilTex: 'plates' },
    stair: { floor: 16, ceil: 224, light: '#c07a38', lightTop: '#401808', floorTex: 'grate', ceilTex: 'plates', wallTex: 'tech' },
    platform: { floor: 32, ceil: 224, light: '#d08a40', lightTop: '#401808', floorTex: 'grate', ceilTex: 'plates', wallTex: 'tech' },
    chapel: { floor: 0, ceil: 256, light: '#6a2050', lightTop: '#200818', floorTex: 'flagstone', ceilTex: 'plates' },
    ante: { floor: 0, ceil: 128, light: '#8a5030', lightTop: '#2a0810', floorTex: 'flagstone', ceilTex: 'plates' },
    sigil: { floor: 0, ceil: 128, light: '#e0a050', lightTop: '#3a0810', floorTex: 'exit', ceilTex: 'plates' },
  },
  legend: {
    '#': { wall: 'brick' },
    M: { wall: 'metal' },
    T: { wall: 'tech' },
    X: { wall: 'tech' },
    a: { sector: 'crypt' },
    b: { sector: 'duct' },
    h: { sector: 'hall' },
    o: { sector: 'altar' },
    s: { sector: 'slime' },
    w: { sector: 'walkway' },
    l: { sector: 'ledge' },
    v: { sector: 'vault' },
    f: { sector: 'furnace' },
    k: { sector: 'stair' },
    K: { sector: 'platform' },
    c: { sector: 'chapel' },
    e: { sector: 'ante' },
    x: { sector: 'sigil', exit: true },
    D: { sector: 'doorway', door: { tex: 'door' } },
    R: { sector: 'doorway', door: { tex: 'door_red', key: 'red' } },
    B: { sector: 'doorway', door: { tex: 'door_blue', key: 'blue' } },
  },
  spawn: [4, 5, 0],
  rows: [
"""

here = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(here, '..', 'src', 'levels', 'charnel.ts'), 'w', encoding='utf8') as f:
    f.write(HEADER + rows + ',\n  ],\n  things: [\n' + things_ts + ',\n  ],\n};\n')
print('\n'.join(''.join(r) for r in out))
